# Pytorch

Pytorch is a machine learning libary that was developed using torch (Torch is scientific computing libary developed using Lua by Meta). To get started install pytorch library using command that was generated in this link.

**https://pytorch.org/get-started/locally/**

## Installation

### CUDA Supported Nvidia GPUs

If you want to train your models locally on pytorch using GPU then your GPU should support CUDA (For). To check if your GPU is supports CUDA or not, you can check if your GPU is listed in RTX/Geforce section here: **https://developer.nvidia.com/cuda-gpus**. The compute capability is not the cuda version so you can ignore it.

If you have an Nvidia GPU that has CUDA cores then select the options below and copy the command and run in your pc to install the pytorch library


![torch_image](./images/Nvidia_GPU.png)

### AMD GPUs

If your PC has AMD GPU and you want to train your models on GPU then you need to install ROCm supported Pytorch package. But first check if your GPU supports latest version of ROCm here **https://rocm.docs.amd.com/en/latest/** under windows/linux overview section.

![AMD](./images/AMD_GPU.png)

### Intel/Unsupported GPUs/CPU Installation

If your GPU isn't supported then you will have to go with CPU installation. So you would need to select CPU and run the command

![Unsupported](./images/torch_CPU.png)

To check your installation import the library using the command

In [1]:
import torch

# Detecing your GPU

If your GPU is supported and you want to check if your Pytorch installation detects GPU or not, you can run this command

In [2]:
torch.cuda.is_available()

True

It would give `True` otherwise it would be `False`

# Rank 0 Tensor (Scalar)

To initialize a scaler using torch


In [3]:
scalar_value = torch.tensor(2)
display(scalar_value) # Displays the output (similar to print) in the notebook

# Dimension of scalar_value

display(scalar_value.shape)

# Data type of the scalar_value
type(scalar_value)

tensor(2)

torch.Size([])

torch.Tensor

In the above cell we can see that the tensor itself is a scalar value because it returns an empty array when we ask for shape of the tensor. And if we check the datatype of the scalar value we can see that it is a torch tensor object. We can also change the datatype of scaler value by passing the torch datatype in the `dtype` argument

You can check more datatypes here: https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype

In [4]:
scalar_value = torch.tensor(2, dtype=torch.float64) # 64 bit float datatype
display(scalar_value) # Displays the output (similar to print) in the notebook

scalar_value = torch.tensor(2, dtype=torch.float32) # 32 bit float datatype
display(scalar_value)

scalar_value = torch.tensor(2, dtype=torch.int64) # 64 bit Integer datatype
display(scalar_value)


tensor(2., dtype=torch.float64)

tensor(2.)

tensor(2)

# Rank 1 Tensor (Vector)

To initialize a vector/ rank-1 tensor using torch

In [5]:
vector = torch.tensor([1, 2, 3, 4, 5])
display(vector)
display(vector.shape)

# Mentioning the datatype when initializing the tensor
vector = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float64)
display(vector)

# Initializing zeros vector
zeros_vector = torch.zeros(5)
display(zeros_vector)

# Initialzing ones vector
ones_vector = torch.ones(5)
display(ones_vector)

# Initializing vector with random values
rand_vector = torch.randn(5)
display(rand_vector)

tensor([1, 2, 3, 4, 5])

torch.Size([5])

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)

tensor([0., 0., 0., 0., 0.])

tensor([1., 1., 1., 1., 1.])

tensor([-1.2715,  1.7954,  1.3911, -0.2118,  1.1912])

# Rank 2 Tensor (Matrix)

In [6]:
rank_2_tensor = torch.tensor([[1, 2,],[3, 4]])
display(rank_2_tensor)
display(rank_2_tensor.shape)

# Mentioning the datatype when initializing the tensor
rank_2_tensor = torch.tensor([[1, 2],[3, 4]], dtype=torch.float64)
display(rank_2_tensor)

# Initializing zeros matrix
zeros_matrix = torch.zeros((2, 3))
display(zeros_matrix)

# Initialzing ones matrix
ones_matrix = torch.ones((2, 3))
display(ones_matrix)

# Initializing tensor with random values
rand_matrix = torch.randn((2, 3))
display(rand_matrix)

tensor([[1, 2],
        [3, 4]])

torch.Size([2, 2])

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[-0.2052, -0.3188,  0.1485],
        [ 0.4797,  0.3248, -1.0792]])

# Simple Tensor Operations

In [7]:
A = torch.ones((2, 3))
B = torch.zeros((2, 3))

display(A)
display(B)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## Concatenation of two Tensors

In [8]:
row_wise_concat = torch.cat([A, B], dim=0) # Row-wise concatenation
display(row_wise_concat)
display(row_wise_concat.shape)

column_wise_concat = torch.cat([A, B], dim=1) # Column-wise concatenation
display(column_wise_concat)
display(column_wise_concat.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

torch.Size([4, 3])

tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])

torch.Size([2, 6])

# Stacking tensors

In [9]:
display(torch.stack([A, B], dim=0))
torch.stack([A, B], dim=0).shape

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

torch.Size([2, 2, 3])

In [10]:
display(torch.stack([A, B], dim=1))
torch.stack([A, B], dim=1).shape

tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]]])

torch.Size([2, 2, 3])

In [11]:
display(torch.stack([A, B], dim=2))
torch.stack([A, B], dim=1).shape

tensor([[[1., 0.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.],
         [1., 0.]]])

torch.Size([2, 2, 3])

# Mathematical Operations

In [12]:
X = torch.randn((2, 3))
Y = torch.randn((2, 3))

display(X + Y, X - Y, X * Y, X / Y)

tensor([[ 0.2060, -1.6944, -2.1107],
        [-0.8241,  0.5678,  0.1780]])

tensor([[-2.3461, -0.8867, -0.6894],
        [ 0.2026, -1.1793,  0.3061]])

tensor([[-1.3655,  0.5212,  0.9949],
        [ 0.1595, -0.2671, -0.0155]])

tensor([[-0.8386,  3.1958,  1.9700],
        [ 0.6053, -0.3500, -3.7794]])

# Element wise multiplication

In [13]:
A = torch.randn([2, 2])
B = torch.randn([2, 2])

display(A, B, A*B)

tensor([[-0.0736, -1.4861],
        [ 0.2065,  0.1480]])

tensor([[ 1.7124,  1.1003],
        [-0.2198,  0.5201]])

tensor([[-0.1260, -1.6352],
        [-0.0454,  0.0769]])

In [14]:
display(A * B, torch.mul(A, B), A.mul(B))

tensor([[-0.1260, -1.6352],
        [-0.0454,  0.0769]])

tensor([[-0.1260, -1.6352],
        [-0.0454,  0.0769]])

tensor([[-0.1260, -1.6352],
        [-0.0454,  0.0769]])

# Matrix multiplication

In [15]:
display(A @ B, torch.matmul(A, B), A.matmul(B))

tensor([[ 0.2006, -0.8538],
        [ 0.3211,  0.3042]])

tensor([[ 0.2006, -0.8538],
        [ 0.3211,  0.3042]])

tensor([[ 0.2006, -0.8538],
        [ 0.3211,  0.3042]])

# Dot Product

In [16]:
A = torch.randn(5)
B = torch.randn(5)

display(torch.dot(A, B)) # Dot product

tensor(3.0826)