# Leaf Tensors and Gradients

In [4]:
import torch
import numpy as np
import pandas as pd

## Leaf Tensors

![image.png](images/Leaf.png)

In [9]:
a = torch.tensor([2, 3], dtype=torch.float32, requires_grad=True)
print(f'a: {a.is_leaf}')
b = a**2 + 2*a # Here b is a computed tensor of a
print(f'b: {b.is_leaf}')

a: True
b: False


In [2]:
w = torch.tensor([1, 2], dtype=torch.float32, requires_grad=True)
b = torch.ones(2).requires_grad_() # Using requires_grad_() function we initialized requires_grad = True for that tensor.

print(f'w: {w.is_leaf},  b: {b.is_leaf}')

w: True,  b: True


In [10]:
x = w@b + b
x.is_leaf

False

In [11]:
w = torch.tensor([1, 2], dtype=torch.float32, requires_grad=True)
b = torch.ones(2)
display(w, b)

tensor([1., 2.], requires_grad=True)

tensor([1., 1.])

In [12]:
b.requires_grad_()
b

tensor([1., 1.], requires_grad=True)

In [13]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([-1, 1], dtype=torch.float32)

def linreg(x):
    return w @ x + b

preds = linreg(x)
preds

tensor([ 8., 11.], grad_fn=<AddBackward0>)

In [14]:
# Calculating sum of squares of errors
def SSE(preds, y):
    return (y - preds).pow(2).sum()

loss = SSE(preds, y)
loss

tensor(181., grad_fn=<SumBackward0>)

In [15]:
loss.is_leaf

False

To calculate the gradients of those leaf tensors (that have `requires_grad = True`), we use a function called `backward()`.

In [16]:
loss.backward()

In [17]:
display(w.grad, b.grad)

tensor([ 58., 134.])

tensor([18., 20.])

In [9]:
display(x.is_leaf, y.is_leaf)
display(preds.is_leaf)

True

True

False

In [10]:
preds.requires_grad_()

tensor([ 8., 11.], grad_fn=<AddBackward0>)

In [11]:
preds.detach()

tensor([ 8., 11.])

In [38]:
a = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)
a.is_leaf

True

In [37]:
c = a*a
d = a**2
print(c, d)

tensor([1., 4., 9.], grad_fn=<MulBackward0>) tensor([1., 4., 9.], grad_fn=<PowBackward0>)


In [35]:
x = torch.ones(3)*(b -a)
x

tensor([2., 2., 0.], grad_fn=<MulBackward0>)

In [27]:
a

tensor([1., 2., 3.], requires_grad=True)

In [30]:
a = a*a
a.is_leaf

False